---

- name: Verify KOMPOSE exists
  stat: path=/opt/kompose/kompose-linux-amd64
  register: kompose_stat

- name: Configure KOMPOSE on system bin.
  file:
    src: "/opt/kompose/kompose-linux-amd64"
    dest: "/usr/bin/kompose"
    state: link
  when: kompose_stat.stat.exists

- name: Configure KOMPOSE on system sbin.
  file:
    src: "/opt/kompose/kompose-linux-amd64"
    dest: "/usr/sbin/kompose"
    state: link
  when: kompose_stat.stat.exists

- command: kompose version
  register: result
  failed_when: false
  changed_when: false